### ISSUE TITLE
Remove SSH instructions for Hydra

### ISSUE THREAD

**Issue by dstansby** [NGIOproject/nextgenio-docs#3]
https://ngioproject.github.io/nextgenio-docs/html/user_guide/connect.html#copy-the-public-part-of-the-key-to-the-remote-host has instructions on how to use SSH keys with Hydra, but when I log in to Hydra I get the following message:
```
================================================================================

Hydra Cluster (Hydra-VPN) HPC Service



       This system is now password access only and ssh keys are not used.


       Please reset your password using the SAFE at

           https://safe.epcc.ed.ac.uk


       For help please contact the service helpdesk at: 

           epcc-support@epcc.ed.ac.uk




================================================================================
```

I got a bit confused trying to use my SSH key as per the `nextgenio` docs until I read this message, so it would be good to remove the section in the `nextgenio` docs about using SSH keys with Hydra since it seems this is not supported.

**Comment by adrianjhpc** [comment]
Done
